### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/fenton_adsorption_SOM#1]
1. Native SOM composition

- [ ] Van Krevelen HW and SW
- [ ] Summary table of groups
- [ ] Summary table of elemental composition

2. Fenton changes
- [ ] summary table of groups and elemental composition
- [ ] summary table of new and lost compounds
- [ ] NOSC

3. Goethite changes
- [ ] summary table of groups and elemental composition
- [ ] summary table of new and lost compounds [Fenton and non-Fenton]
- [ ] NOSC
